# SwiftLint Configuration for KYC Form Package

# Include all Swift sources
included:
  - Sources
  - Tests

# Explicitly exclude dependencies and build artifacts
excluded:
  - .build
  - .swiftpm
  - DerivedData
  - Packages  # Swift Package Manager dependencies
  - .dependencies
  - checkouts
  - Dependencies
  - "**/Dependencies/**"
  - "**/.build/**"
  - "**/Packages/**"
  - "**/checkouts/**"

# Enabled rules (start conservative, add more over time)
opt_in_rules:
  - anyobject_protocol
  - array_init
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - comma_inheritance
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - file_name_no_space
  - first_where
  - force_unwrapping
  - implicit_return
  - joined_default_parameter
  - let_var_whitespace
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - nimble_operator
  - operator_usage_whitespace
  - overridden_super_call
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - vertical_parameter_alignment_on_call
  - yoda_condition

# Disabled rules (can be enabled later)
disabled_rules:
  - todo # Allow TODO comments during development
  - line_length # Will configure separately

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 800

type_body_length:
  warning: 300
  error: 500

function_body_length:
  warning: 40
  error: 60

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 2
    error: 3

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - vm
    - ui
    - nl
    - de
    - us

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 40
    error: 50

large_tuple:
  warning: 3
  error: 4

# Force unwrapping configuration
force_unwrapping:
  severity: warning

# Custom rules for package
custom_rules:
  no_print:
    name: "No Print Statements"
    regex: '\bprint\('
    message: "Use proper logging instead of print statements"
    severity: warning
